#!/bin/sh

echo ""
echo "flac2alac - script to convert FLAC audio to ALAC"
echo "By Arlindo \"Nighto\" Pereira"
echo "<nighto@nighto.net>"
echo "(C) 2010. Licensed on GPLv3"
echo ""

if [ "$1" ]
then
	ffmpeg  -i "$1" -acodec alac "`basename "$1" .flac`.m4a" \
		-metadata title=\""$(metaflac --show-tag=TITLE "$1" | sed 's/TITLE=//g' | sed 's/title=//g')"\" \
		-metadata author=\""$(metaflac --show-tag=ARTIST "$1" | sed 's/ARTIST=//g' | sed 's/artist=//g')"\" \
		-metadata album=\""$(metaflac --show-tag=ALBUM "$1" | sed 's/ALBUM=//g' | sed 's/album=//g')"\" \
		-metadata year=\""$(metaflac --show-tag=DATE "$1" | sed 's/DATE=//g' | sed 's/date=//g')"\" \
		-metadata track=\""$(metaflac --show-tag=TRACKNUMBER "$1" | sed 's/TRACKNUMBER=//g' | sed 's/tracknumber=//g')"\" \
		-metadata genre=\""$(metaflac --show-tag=GENRE "$1" | sed 's/GENRE=//g' | sed 's/genre=//g')"\"
else
	echo "Usage:"
	echo "flac2alac file.flac"
	echo ""
exit 1
fi
